# Sequel Database Configuration

development:
  host: localhost
  port: 27017
  database: todo_development
  username:
  password:

test:
  host: localhost
  port: 27017
  database: todo_test
  username:
  password:

production:
  host: localhost
  port: 27017
  database: todo_production
  username:
  password:

