source "https://rubygems.org/"

# App Stack
gem "sinatra", "~> 1.4"

# Database Stack
gem "bson_ext", "~> 1.8"
gem "mongodb_model", "~> 2.1"
gem "mongoid"
gem "database_cleaner"

group :development do
  gem "rake", "~> 10.0"
  gem "rspec"
  gem "rack-test", "~> 0.6"
end
