source "https://rubygems.org/"

# App Stack
gem "sinatra", "~> 1.4"

# Database Stack
gem "bson_ext", "~> 1.8"
gem "mongodb_model", "~> 2.1"

group :development do
  gem "rake", "~> 10.0"
  gem "minitest", "~> 5.2"
  gem "rack-test", "~> 0.6"
end
